[package]
name = "victron_ble"
version = "0.1.0"
edition = "2021"

[dependencies]
bluez-async = "0.7.2"
aes = "0.8.4"
ctr = "0.9.2"
thiserror = "1.0.64"
num_enum = "0.7.3"

[dev-dependencies]
hex = "0.4"
futures = "0.3.31"
tokio = { version =  "1.40.0", features=["full"] }
